#!/bin/sh
#/ Usage: bootstrap [bundle options]
#/
#/ Bundle install the dependencies.
#/
#/ Examples:
#/
#/   bootstrap
#/   bootstrap --local
#/

set -e
cd $(dirname "$0")/..

[ "$1" = "--help" -o "$1" = "-h" -o "$1" = "help" ] && {
    grep '^#/' <"$0"| cut -c4-
    exit 0
}

rm -rf .bundle/{binstubs,config}

# https://issues.apache.org/jira/browse/THRIFT-2219
bundle config --local build.thrift --with-cppflags=-D_FORTIFY_SOURCE=0
bundle install --binstubs .bundle/binstubs --path .bundle --quiet "$@"
