#!/bin/sh
#/ Usage: test
#/
#/ Bootstrap and run all tests.
#/
#/ Examples:
#/
#/   # run all tests
#/   test
#/

set -e
cd $(dirname "$0")/..

[ "$1" = "--help" -o "$1" = "-h" -o "$1" = "help" ] && {
    grep '^#/' <"$0"| cut -c4-
    exit 0
}

specs="spec/"

if [ $# -gt 0 ]
  then
    specs=$@
fi

script/bootstrap && bundle exec rake unattended_spec
